package mx.test.android.gonet.domainlib.models

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import mx.test.android.gonet.domainlib.models.child.*

@Parcelize
data class TvShowDetailModel(
    var backdropPath: String,
    var createdBy: List<CreatedBy>,
    var episodeRunTime: List<Int>,
    var firstAirDate: String,
    var genres: List<Genre>,
    var homepage: String,
    var id: Int,
    var inProduction: Boolean,
    var languages: List<String>,
    var lastAirDate: String,
    var lastEpisodeToAir: LastEpisodeToAir,
    var name: String,
    var networks: List<Network>,
    var numberOfEpisodes: Int,
    var numberOfSeasons: Int,
    var originCountry: List<String>,
    var originalLanguage: String,
    var originalName: String,
    var overview: String,
    var popularity: Double,
    var posterPath: String,
    var productionCompanies: List<ProductionCompany>,
    var productionCountries: List<ProductionCountry>,
    var seasons: List<Season>,
    var spokenLanguages: List<SpokenLanguage>,
    var status: String,
    var tagline: String,
    var type: String,
    var voteAverage: Double,
    var voteCount: Int,
) : Parcelable {
    constructor() : this(
        backdropPath = "",
        createdBy = listOf<CreatedBy>(),
        episodeRunTime = listOf<Int>(),
        firstAirDate = "",
        genres = listOf<Genre>(),
        homepage = "",
        id = -1,
        inProduction = false,
        languages = listOf<String>(),
        lastAirDate = "",
        lastEpisodeToAir = LastEpisodeToAir(),
        name = "",
        networks = listOf<Network>(),
        numberOfEpisodes = -1,
        numberOfSeasons = -1,
        originCountry = listOf<String>(),
        originalLanguage = "",
        originalName = "",
        overview = "",
        popularity = -1.0,
        posterPath = "",
        productionCompanies = listOf<ProductionCompany>(),
        productionCountries = listOf<ProductionCountry>(),
        seasons = listOf<Season>(),
        spokenLanguages = listOf<SpokenLanguage>(),
        status = "",
        tagline = "",
        type = "",
        voteAverage = -1.0,
        voteCount = -1
    )
}